// Initially generated by GPT-5.4 mini

import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const modPath = path.resolve("./tinymist/pkg/tinymist.js");
const mod = await import(pathToFileURL(modPath));

const wasmPath = path.resolve("./tinymist/pkg/tinymist_bg.wasm");
const wasmBytes = await fs.readFile(wasmPath);

const init = mod.default ?? mod.init;
if (!init) throw new Error("No init function found in tinymist module");

export default async function() {
  await init(wasmBytes)
}

export * from "./tinymist/pkg/tinymist.js";
